# Generated by Django 2.1.7 on 2019-08-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('company', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('graduated', models.CharField(max_length=128)),
            ],
        ),
    ]
